vich_uploader:
    db_driver: orm
    
    mappings:
        fichaTecnica_imagem:
            uri_prefix: /images/fichaTecnica
            upload_destination: '%kernel.project_dir%/public/images/fichaTecnica'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: App\Controller\VichUploaderFichaTecnicaImagemDirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
